name = "subconverter-loadbalancer"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "subconverter-db"
database_id = "a34f0c72-013c-4875-a814-1d5ccbd6279f"

# 增加日志配置
[log_filters]
level = "info"

# Observability 配置
[observability]
enabled = true